task_3 solution
mate-academy/py-linter-formatter pull request #1001
Opened 2023-12-02 11:00 UTC by ruslan-sketch

Вирішив задачу linter-formatter. Прошу перевірити.

2023-12-02 12:26 UTC, ArsenPidhoretskyi requested changes
Task is not properly completed

2023-12-02 12:26 UTC, ArsenPidhoretskyi commented on app/main.py
> +        return {}
This is redundant

2023-12-02 12:26 UTC, ArsenPidhoretskyi commented on app/main.py
> +    return formatted_error
```suggestion
    return {
        "line": error["line_number"],
        "column": error["column_number"],
        "message": error["text"],
        "name": error["code"],
        "source": "flake8"
    }
```
Please read task again: All functions must contain only the return keyword

2023-12-02 12:26 UTC, ArsenPidhoretskyi commented on app/main.py
> +            }
Reuse format_linter_error

2023-12-02 12:26 UTC, ArsenPidhoretskyi commented on app/main.py
> +    return result
Reuse format_single_linter_file

2023-12-02 16:02 UTC, ruslan-sketch commented
виправив синтаксичні помилки згідно flak8.

2023-12-02 20:40 UTC, ruslan-sketch commented
ще виправив помилки

2025-03-26 18:17 UTC, ruslan-sketch commented
Пише-немає конфліктів. А завдання висить незакрите. В чому справа? Дякую

2025-06-19 13:54 UTC, closed without merging