'Solution'
mate-academy/py-linter-formatter pull request #1321
Opened 2024-03-26 11:26 UTC by Alex2016AVI

2024-03-26 12:17 UTC, ArsenPidhoretskyi requested changes

2024-03-26 12:17 UTC, ArsenPidhoretskyi commented on app/main.py
> +                    "source": "flake8"} for error in errors],
Reuse format_linter_error and pass error instead of code duplicate

2024-03-26 12:17 UTC, ArsenPidhoretskyi commented on app/main.py
> +    return [{"errors": [{"line": error["line_number"],
Reuse format_single_linter_file instead of code duplicate

2024-04-10 08:22 UTC, EdAlekseiev approved these changes

2024-12-04 16:29 UTC, closed without merging