linter-formatter
mate-academy/py-linter-formatter pull request #1337
Opened 2024-04-07 09:41 UTC by NikitaNikolaitsev

2024-05-13 08:28 UTC, wQuelS requested changes

2024-05-13 08:28 UTC, wQuelS commented on app/main.py
> +from typing import Dict, List
why have you decided to use `typing` module for such simple type hinting?

2024-05-13 08:28 UTC, wQuelS commented on app/main.py
> +            for file_path, errors in linter_report.items()]
Your dictionaries and list, are formatted correctly, but they should use one style. 
Please, remain consistent and choose one formatting approach to use everywhere.

2024-05-15 06:14 UTC, DevSpaciX approved these changes

2024-05-15 06:14 UTC, DevSpaciX commented on app/main.py
> +        "status": "failed" if len(errors) else "passed"
You can check if errors exists  more simply -> if errors
But other code looks good for now : )

2024-05-15 06:20 UTC, DevSpaciX requested changes

2024-05-15 06:20 UTC, DevSpaciX commented on app/main.py
>  def format_linter_error(error: dict) -> dict:
Fix pls failed tests :)

2024-05-15 13:49 UTC, Oleg-s-s approved these changes
:+1:

2024-09-30 11:28 UTC, closed without merging