Solution
mate-academy/py-linter-formatter pull request #1565
Opened 2024-08-07 15:40 UTC by ShiftRomero

2024-08-07 18:17 UTC, vsmutok requested changes

2024-08-07 18:17 UTC, vsmutok commented on app/main.py
> +            "status": "failed" if errors != [] else "passed"}
```suggestion
    return {
        "errors": [format_linter_error(error) for error in errors],
        "path": file_path,
        "status": "failed" if errors else "passed"
    }
```

2024-08-07 18:17 UTC, vsmutok commented on app/main.py
> +            for key, value in linter_report.items()]
` key, value` - bad variables names

2024-08-08 16:56 UTC, ShiftRomero commented on app/main.py
> +            for key, value in linter_report.items()]
Доброго вечора, не розумію суть проблеми у мене пройшли всі перевірки(pytest, flake8).В результаті застосування ваших змін .\app\main.py:22:60: F821 undefined name 'errors'
.\app\main.py:23:17: F821 undefined name 'file_path'
.\app\main.py:24:31: F821 undefined name 'errors'
Ну то і це логічно

2024-08-16 16:11 UTC, closed without merging