Solution (-2 tests)
mate-academy/py-linter-formatter pull request #17
Opened 2022-01-13 22:17 UTC by exlawyer

2022-01-14 08:20 UTC, MasterpieceElbow requested changes

2022-01-14 08:20 UTC, MasterpieceElbow commented on app/main.py
> +    return {file_path: format_linter_error(errors)}
'format_linter_error' takes only 1 error and you call it with a list of errors. 
'format_single_file' should return data like:
<img width="527" alt="Снимок экрана 2022-01-14 в 10 11 33" src="https://user-images.githubusercontent.com/80070761/149473924-4b4cf78c-d651-48d2-a18e-f0efeea61b07.png">

2022-01-14 08:20 UTC, MasterpieceElbow commented on app/main.py
> +    ]
You return a list only with 1 element, you have to return a list with all files

2022-01-14 08:20 UTC, MasterpieceElbow commented on app/main.py
> +            "status": "passed"
Why do you have static "status": "passed"? Status depends on file has errors or not.

2022-01-14 08:20 UTC, MasterpieceElbow commented on app/main.py
> +        }
This dict should be returned by 'format_single_linter_file'

2022-01-15 07:53 UTC, danylott commented on app/main.py
Also formatting is not very well :(
Try to do next:
```python
return {
  "key1": "value1",
  "key2": "value2",
}
```

2022-01-17 07:35 UTC, danylott requested changes

2022-01-17 07:35 UTC, danylott commented on app/main.py
> +    return {"errors": [format_linter_error(i) for i in errors], "path": file_path, "status": "passed" if len(errors) == 0 else "failed"}
Bad code style here - line is too long:
app/main.py:12:80: E501 line too long (136 > 79 characters)

2022-01-17 07:35 UTC, danylott commented on app/main.py
> +    return list(
why list() not []

2022-01-17 10:18 UTC, exlawyer commented on app/main.py
> +    return list(
та не знаю что взяв list. якось автоматом вийшло) я вбив на цю задачу купу часу і коли пройшло усі тести, то я вже від радості не сильно і дивився на варіанти)

2022-01-17 10:19 UTC, exlawyer commented on app/main.py
> +    return list(
я поправив і тут і вище це довгий рядок

2023-03-07 16:20 UTC, closed without merging