Solution
mate-academy/py-linter-formatter pull request #228
Opened 2022-09-20 09:32 UTC by y-satskyi

2022-09-20 09:36 UTC, IvanRamyk requested changes
A few code-style suggestions

2022-09-20 09:36 UTC, IvanRamyk commented on app/main.py
> +            "source": "flake8"}
```suggestion
    return {
        "line": error["line_number"],
        "column": error["column_number"],
        "message": error["text"] ,
        "name": error["code"],
        "source": "flake8"
    }
```

2022-09-20 09:36 UTC, IvanRamyk commented on app/main.py
> +            "status": ("passed" if len(errors) == 0 else "failed")}
```suggestion
    return {
        "errors": [format_linter_error(error) for error in errors],
        "path": file_path,
        "status": ("passed" if len(errors) == 0 else "failed")
    }
```

2022-09-20 09:36 UTC, IvanRamyk commented on app/main.py
> +        for key, value in linter_report.items()]
fix here as well

2022-09-20 11:50 UTC, y-satskyi commented
I fixed

2022-09-20 18:40 UTC, closed without merging

2022-10-11 07:03 UTC, y-satskyi commented
Can you check again?
I have already done yesterday