implemented py-linter-formatter
mate-academy/py-linter-formatter pull request #606
Opened 2023-05-23 13:38 UTC by mariiahorbova

2023-05-23 14:56 UTC, Oleg-s-s requested changes

2023-05-23 14:56 UTC, Oleg-s-s commented on app/main.py
> +        "status": "failed" if len(errors) else "passed"
No need to call len() here

2023-05-23 14:56 UTC, Oleg-s-s commented on app/main.py
> +        for (path, errors) in linter_report.items()
Unnecessary brackets
```suggestion
        for path, errors in linter_report.items()
```

2023-05-24 09:32 UTC, LiudmylaKulinchenko approved these changes
Good job! 🐣

2024-03-13 20:01 UTC, closed without merging