Solution of py-linter-formated
mate-academy/py-linter-formatter pull request #640
Opened 2023-05-31 16:52 UTC by vkleshko

2023-05-31 17:07 UTC, vsmutok requested changes

2023-05-31 17:07 UTC, vsmutok commented on app/main.py
> +            }
use `format_linter_error` here

2023-05-31 17:07 UTC, vsmutok commented on app/main.py
> +            "status": "failed" if errors else "passed"
usr `format_single_linter_file` here

2023-07-07 10:29 UTC, vkleshko commented
I fixed all mistakes

2023-07-07 14:15 UTC, closed without merging