Solution
mate-academy/py-linter-formatter pull request #871
Opened 2023-09-26 18:57 UTC by mishagitcode

2023-09-26 19:06 UTC, EdAlekseiev requested changes

2023-09-26 19:06 UTC, EdAlekseiev commented on app/main.py
> +        "status": "failed"
If `errors` is empty list status must be `passed `

2023-09-26 19:06 UTC, EdAlekseiev commented on app/main.py
> +        }
```suggestion
        format_single_linter_file(key, value)
```

2023-09-29 14:42 UTC, Bohdan-Salamakha requested changes

2023-09-29 14:42 UTC, Bohdan-Salamakha commented on app/main.py
> +    }
```suggestion
    return {
        "errors": [format_linter_error(error) for error in errors],
        "path": file_path,
        "status": "failed" if errors else "passed"
    }
```

2023-09-29 14:42 UTC, Bohdan-Salamakha commented on app/main.py
> +    ]
```suggestion
    return [
        format_single_linter_file(file_path, error)
        for file_path, error in linter_report.items()
    ]
```

2023-09-29 15:47 UTC, Bohdan-Salamakha approved these changes

2024-08-14 14:17 UTC, closed without merging