Solution
mate-academy/py-linter-formatter pull request #886
Opened 2023-09-28 08:33 UTC by Katherine-Greg

Виникли помилки з функцією format_linter_report: тест не проходить, але відповідь повертає правильну

2023-09-28 11:00 UTC, RVChornyy approved these changes
Nice!

2023-09-29 09:23 UTC, wQuelS requested changes
![изображение](https://github.com/mate-academy/py-linter-formatter/assets/105493988/e2b35de6-d972-4371-90c2-ee1b0cc79614)
Your formatting style in the first function differs from style in two other functions. Please, try to be consistent with it and provide a fix

2023-10-01 15:59 UTC, Andrii-Silenko commented on app/main.py
> +        format_single_linter_file(key, errors)
Maybe "key" is not the best name of varuable. I'd prefer "file_path" or "path_of_file

2023-10-01 16:01 UTC, Andrii-Silenko commented on app/main.py
> +        "status": "failed" if len(errors) > 0 else "passed"
It's ok, but you can rewrite this condition as:
```suggestion
        "status": "failed" if len(errors) > 0 else "passed"
```

2023-10-01 16:02 UTC, Andrii-Silenko commented on app/main.py
> +        "status": "failed" if len(errors) > 0 else "passed"
You can rewrite this condition as:
```suggestion
        "status": "failed" if errors else "passed"
```

2023-10-01 16:05 UTC, Andrii-Silenko approved these changes

2023-10-04 20:29 UTC, RVChornyy approved these changes

2023-10-05 09:43 UTC, fsocie7y approved these changes

2023-10-05 09:43 UTC, fsocie7y commented on app/main.py
> +        "errors": [format_linter_error(errors[i])
in cases like this u can use `for element in elements: ...` without indexes

2023-10-05 09:45 UTC, closed without merging